#!/bin/bash

for FILE in schema/runconf-schema/*.proto;
do
    echo "Generating protocols for ${FILE}"

    python -m grpc_tools.protoc \
        --proto_path=./schema/ \
        --python_out=src/ \
        --grpc_python_out=src/ \
        --mypy_out=src/ \
	    --mypy_grpc_out=src/ \
        ${FILE}

    # FILE_NAME=$(basename -- "$FILE")
    # CLASS_NAME="${FILE_NAME%.*}"
    # PY_OUT_FILE_NAME="python/runconf-schema/${CLASS_NAME}_pb2_grpc.py"
    # sed -i '' "/google/! s/import \(.*_pb2\)/import runconf-schema.\1/" ${PY_OUT_FILE_NAME}
    # PY_OUT_FILE_NAME="python/runconf-schema/${CLASS_NAME}_pb2.py"
    # sed -i '' "/google/! s/import \(.*_pb2\)/import runconf-schema.\1/" ${PY_OUT_FILE_NAME}
done

for FILE in schema/runconf-schema/opmon/*.proto;
do
    echo "Generating protocols for ${FILE}"

    python -m grpc_tools.protoc \
        --proto_path=./schema/ \
        --python_out=src/ \
        --mypy_out=src/ \
	    --mypy_grpc_out=src/ \
        ${FILE}

    # FILE_NAME=$(basename -- "$FILE")
    # CLASS_NAME="${FILE_NAME%.*}"
    # PY_OUT_FILE_NAME="python/runconf-schema/${CLASS_NAME}_pb2_grpc.py"
    # sed -i '' "/google/! s/import \(.*_pb2\)/import runconf-schema.\1/" ${PY_OUT_FILE_NAME}
    # PY_OUT_FILE_NAME="python/runconf-schema/${CLASS_NAME}_pb2.py"
    # sed -i '' "/google/! s/import \(.*_pb2\)/import runconf-schema.\1/" ${PY_OUT_FILE_NAME}
done
